version: "3.8"

services:
  jest:
    build: .
    container_name: jest
    volumes:
      - .:/academic_performance
      - /academic_performance/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: yarn testFinal --ci --runInBand
